# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'admin'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['strest-tokio', 'strest-master']
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: ^admin-http$
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [ __meta_kubernetes_pod_label_strest_profile]
        action: replace
        target_label: strest_profile
      - source_labels: [__meta_kubernetes_pod_label_strest_role]
        action: replace
        target_label: strest_role

    - job_name: 'grafana'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['strest-tokio-conduit']
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_container_name
        action: keep
        regex: ^grafana$

    # from https://grafana.com/dashboards/315
    - job_name: kubernetes-nodes-cadvisor
      scheme: https  # remove if you want to scrape metrics on insecure port
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      # Only for Kubernetes ^1.7.3.
      # See: https://github.com/prometheus/prometheus/issues/2916
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      metric_relabel_configs:
      - action: replace
        source_labels: [id]
        regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
        target_label: rkt_container_name
        replacement: '${2}-${1}'
      - action: replace
        source_labels: [id]
        regex: '^/system\.slice/(.+)\.service$'
        target_label: systemd_service_name
        replacement: '${1}'

    - job_name: 'conduit-controller'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['strest-tokio-conduit']
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_conduit_io_control_plane_component
        - __meta_kubernetes_pod_container_port_name
        action: keep
        regex: (.*);admin-http$
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: component

    - job_name: 'conduit-proxy'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_container_name
        - __meta_kubernetes_pod_container_port_name
        action: keep
        regex: ^conduit-proxy;conduit-metrics$
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      # special case k8s' "job" label, to not interfere with prometheus' "job"
      # label
      # __meta_kubernetes_pod_label_conduit_io_proxy_job=foo =>
      # k8s_job=foo
      - source_labels: [__meta_kubernetes_pod_label_conduit_io_proxy_job]
        action: replace
        target_label: k8s_job
      # __meta_kubernetes_pod_label_conduit_io_proxy_deployment=foo =>
      # deployment=foo
      - action: labelmap
        regex: __meta_kubernetes_pod_label_conduit_io_proxy_(.+)
      # drop all labels that we just made copies of in the previous labelmap
      - action: labeldrop
        regex: __meta_kubernetes_pod_label_conduit_io_proxy_(.+)
      # __meta_kubernetes_pod_label_foo=bar => foo=bar
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
kind: ConfigMap
metadata:
  annotations:
    conduit.io/created-by: conduit/cli git-82e6f717
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval: 10s\n  scrape_timeout: 10s\n  evaluation_interval: 10s\n\nscrape_configs:\n- job_name: 'prometheus'\n  static_configs:\n  - targets: ['localhost:9090']\n\n- job_name: 'grafana'\n  kubernetes_sd_configs:\n  - role: pod\n    namespaces:\n      names: ['strest-tokio-conduit']\n  relabel_configs:\n  - source_labels:\n    - __meta_kubernetes_pod_container_name\n    action: keep\n    regex: ^grafana$\n\n# from https://grafana.com/dashboards/315\n- job_name: kubernetes-nodes-cadvisor\n  scheme: https  # remove if you want to scrape metrics on insecure port\n  tls_config:\n    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token\n  kubernetes_sd_configs:\n  - role: node\n  relabel_configs:\n  - action: labelmap\n    regex: __meta_kubernetes_node_label_(.+)\n  # Only for Kubernetes ^1.7.3.\n  # See: https://github.com/prometheus/prometheus/issues/2916\n  - target_label: __address__\n    replacement: kubernetes.default.svc:443\n  - source_labels: [__meta_kubernetes_node_name]\n    regex: (.+)\n    target_label: __metrics_path__\n    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor\n  metric_relabel_configs:\n  - action: replace\n    source_labels: [id]\n    regex: '^/machine\\.slice/machine-rkt\\\\x2d([^\\\\]+)\\\\.+/([^/]+)\\.service$'\n    target_label: rkt_container_name\n    replacement: '${2}-${1}'\n  - action: replace\n    source_labels: [id]\n    regex: '^/system\\.slice/(.+)\\.service$'\n    target_label: systemd_service_name\n    replacement: '${1}'\n\n- job_name: 'conduit-controller'\n  kubernetes_sd_configs:\n  - role: pod\n    namespaces:\n      names: ['strest-tokio-conduit']\n  relabel_configs:\n  - source_labels:\n    - __meta_kubernetes_pod_label_conduit_io_control_plane_component\n    - __meta_kubernetes_pod_container_port_name\n    action: keep\n    regex: (.*);admin-http$\n  - source_labels: [__meta_kubernetes_pod_container_name]\n    action: replace\n    target_label: component\n\n- job_name: 'conduit-proxy'\n  kubernetes_sd_configs:\n  - role: pod\n  relabel_configs:\n  - source_labels:\n    - __meta_kubernetes_pod_container_name\n    - __meta_kubernetes_pod_container_port_name\n    action: keep\n    regex: ^conduit-proxy;conduit-metrics$\n  - source_labels: [__meta_kubernetes_namespace]\n    action: replace\n    target_label: namespace\n  - source_labels: [__meta_kubernetes_pod_name]\n    action: replace\n    target_label: pod\n  # special case k8s' \"job\" label, to not interfere with prometheus' \"job\"\n  # label\n  # __meta_kubernetes_pod_label_conduit_io_proxy_job=foo =\u003e\n  # k8s_job=foo\n  - source_labels: [__meta_kubernetes_pod_label_conduit_io_proxy_job]\n    action: replace\n    target_label: k8s_job\n  # __meta_kubernetes_pod_label_conduit_io_proxy_deployment=foo =\u003e\n  # deployment=foo\n  - action: labelmap\n    regex: __meta_kubernetes_pod_label_conduit_io_proxy_(.+)\n  # drop all labels that we just made copies of in the previous labelmap\n  - action: labeldrop\n    regex: __meta_kubernetes_pod_label_conduit_io_proxy_(.+)\n  # __meta_kubernetes_pod_label_foo=bar =\u003e foo=bar\n  - action: labelmap\n    regex: __meta_kubernetes_pod_label_(.+)"},"kind":"ConfigMap","metadata":{"annotations":{"conduit.io/created-by":"conduit/cli git-82e6f717"},"labels":{"conduit.io/control-plane-component":"prometheus"},"name":"prometheus-config","namespace":"strest-tokio-conduit"}}
  creationTimestamp: 2018-05-14T21:35:23Z
  labels:
    conduit.io/control-plane-component: prometheus
  name: prometheus-config
  namespace: strest-tokio-conduit
  resourceVersion: "20881291"
  selfLink: /api/v1/namespaces/strest-tokio-conduit/configmaps/prometheus-config
  uid: b5b8467c-57be-11e8-9f35-42010a8001f7
