groups:
- name: target_deployment_source_deployment:response_latency_ms_bucket
  rules:
  - record: target_deployment_source_deployment:response_latency_ms_bucket:irate30s
    expr: sum (irate(response_latency_ms_bucket[30s]))
          by (target_deployment, le, source_deployment)
  - record: target_deployment_source_deployment:response_latency_ms_bucket:p99
    expr:
      histogram_quantile(0.99, target_deployment_source_deployment:response_latency_ms_bucket:irate30s)
  - record: target_deployment_source_deployment:response_latency_ms_bucket:p90
    expr:
      histogram_quantile(0.95,
      target_deployment_source_deployment:response_latency_ms_bucket:irate30s)
  - record: target_deployment_source_deployment:response_latency_ms_bucket:p50
    expr:
      histogram_quantile(0.50,
      target_deployment_source_deployment:response_latency_ms_bucket:irate30s)

- name: source_deployment:response_latency_ms_bucket
  rules:
  - record: source_deployment:response_latency_ms_bucket:irate30s
    expr: sum (irate(response_latency_ms_bucket[30s]))
          by (le, source_deployment)
  - record: source_deployment:response_latency_ms_bucket:p99
    expr:
      histogram_quantile(0.99,
      source_deployment:response_latency_ms_bucket:irate30s)
  - record: source_deployment:response_latency_ms_bucket:p90
    expr:
      histogram_quantile(0.90,
      source_deployment:response_latency_ms_bucket:irate30s)
  - record: source_deployment:response_latency_ms_bucket:p50
    expr:
      histogram_quantile(0.50,
      source_deployment:response_latency_ms_bucket:irate30s)

- name: target_deployment:response_latency_ms_bucket
  rules:
  - record: target_deployment:response_latency_ms_bucket:irate30s
    expr: sum (irate(response_latency_ms_bucket[30s]))
          by (le, target_deployment)
  - record: target_deployment:response_latency_ms_bucket:p99
    expr:
      histogram_quantile(0.99,
      target_deployment:response_latency_ms_bucket:irate30s)
  - record: target_deployment:response_latency_ms_bucket:p90
    expr:
      histogram_quantile(0.90,
      target_deployment:response_latency_ms_bucket:irate30s)
  - record: target_deployment:response_latency_ms_bucket:p50
    expr:
      histogram_quantile(0.50,
      target_deployment:response_latency_ms_bucket:irate30s)

- name: responses_total
  rules:
  - record: target_deployment:responses_total:irate30s
    expr: sum by(target_deployment) (irate(responses_total[30s]))
