target_deployment:response_latency_ms_bucket:p99 = histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{}[30s])) by (target_deployment,le))
target_deployment:response_latency_ms_bucket:p90 = histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{}[30s])) by (target_deployment,le))
target_deployment:response_latency_ms_bucket:p50 = histogram_quantile(0.50, sum(irate(response_latency_ms_bucket{}[30s])) by (target_deployment,le))
target_deployment:responses_total:irate30s = sum(irate(responses_total{}[30s])) by (target_deployment)
